name: rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./dbgee

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
