name: Publish

on:
  push:
    tags:
      - "cli-v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish binaries
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            dbgee/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get OS name
        id: read_os_name
        shell: bash
        run: |
          echo "OS_RELEASE_NAME=$(uname | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd dbgee
          cargo test --verbose

      - name: Build
        run: |
          cd dbgee
          cargo build --release

      - name: Compress
        run: |
          cd dbgee/target/release
          tar cvzf dbgee-${{ env.OS_RELEASE_NAME }}-x64.tar.gz dbgee

      - name: Read the commit message and use it as a body of the new release
        id: read_release
        shell: bash
        run: |
          release="$(git log $(echo ${{ github.ref }} | grep -o 'cli-v.*') -1 --pretty=format:%B)"  # Use the commit message as the release message
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$release" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dbgee/target/release/dbgee-${{ env.OS_RELEASE_NAME }}-x64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            ${{ env.RELEASE_BODY }}
