name: Publish VSCode Extension

on:
  push:
    tags:
      - "vsc-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vscode-ext

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - name: Publish
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
